# .github/workflows/print-message.yml
name: Print Message Workflow

on:
  push:        # Runs when you push to the repo
    branches:
      - main   # Only on pushes to main branch
  workflow_dispatch:  # Allows you to run it manually from GitHub UI

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Hello Message
        run: echo "Hello from GitHub Actions 🎉"
